"use client"

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"

import {
  convenioSchema,
  type ConvenioFormData,
} from "../_schemas/convenio.schema"
import { conveniosMock, type Convenio } from "../_components/dados-mock"

const booleansFalse = {
  showOnlyEventsTied: false,
  allowXml: false,
  hideXmlTimezone: false,
  allowAuthorization: false,
  allowDelivery: false,
  billSessionsSplitted: false,
  billSessionOpen: false,
  printProceduresAsList: false,
  hidePrintGuidePrice: false,
  hideFinances: false,
  allowRepeatProcedures: false,
  allowChangeProceduresDate: false,
  allowChangeMatmedsDate: false,
  allowChangeProceduresTime: false,
  billGroupedProcedureTeam: false,
  techniqueByProcedure: false,
  allowSequentialItem: false,
  allowFixedPrice: false,
  hideExecutantInfo: false,
  hideMainGuideNumber: false,
  hideItemBilling: false,
  requiredGuideAuthorization: false,
  requiredGuideRequester: false,
  showPatientCpfLotResume: false,
  showAuthorizationDataOnGloss: false,
  allowMatmedCustomRedAcr: false,
  customProcedureViaOverPort: false,
  showPercentRedAcr: false,
}

const emptyConvenio: ConvenioFormData = {
  nome: "",
  nomeEstabelecimentoSUS: "",
  grupoConvenioId: "",
  nomeExibicaoAgenda: "",
  cardNumberStartWith: "",
  cardNumberLength: "",
  period: "",
  allowedUsers: [],
  ...booleansFalse,

  ans: "",
  contractCode: "",
  contractName: "",
  cnes: "",
  codification: "",
  film: "",
  coparticipation: "",
  customProcedureViaPercentage: "",
  customProcedureVia: "3",
  customProcedureViaPercentage2: "",
  customProcedureVia2: "3",
  customProcedureViaPercentage3: "",
  customProcedureVia3: "3",
  taxes: "",
  bankId: "",
  autoincrementLastLote: "",
  sendIntervalStartConsulta: "",
  sendIntervalEndConsulta: "",
  sendIntervalStartSadt: "",
  sendIntervalEndSadt: "",
  sendIntervalStartGhi: "",
  sendIntervalEndGhi: "",
  deadlineExpectancyConsulta: "",
  deadlineExpectancySadt: "",
  deadlineExpectancyGhi: "",
  autoincrementLastGuiaConsulta: "",
  autoincrementLastGuiaSadt: "",
  autoincrementLastGuiaGhi: "",
  tissVersion: "",
  tissMethod: "",
  encodingXml: "",
  webserviceProviderType: "",
  deadlineAttendance: "",
  deliveryAddress: "",
  deliveryTime: "",
  orderGuides: "",

  tomadorCnpj: "",
  tomadorRazaoSocial: "",
  tomadorEnderecoCep: "",
  tomadorEnderecoEndereco: "",
  tomadorEnderecoNumero: "",
  tomadorEnderecoComplemento: "",
  tomadorEnderecoUf: "",
  tomadorEnderecoIbge: "",
  tomadorEnderecoBairro: "",

  contatoSector: "",
  contatoName: "",
  contatoEmail: "",
  contatoPhone: "",
  contatoSector2: "",
  contatoName2: "",
  contatoEmail2: "",
  contatoPhone2: "",
  contatoSector3: "",
  contatoName3: "",
  contatoEmail3: "",
  contatoPhone3: "",

  deadlineSendGlosa: "",
  deadlineExpectancyGlosa: "",
  glosaMethod: "",
}

function convenioToForm(c: Convenio): ConvenioFormData {
  return {
    nome: c.nome,
    nomeEstabelecimentoSUS: c.nomeEstabelecimentoSUS,
    grupoConvenioId: c.grupoConvenioId,
    nomeExibicaoAgenda: c.nomeExibicaoAgenda,
    cardNumberStartWith: c.cardNumberStartWith,
    cardNumberLength: c.cardNumberLength,
    showOnlyEventsTied: c.showOnlyEventsTied,
    period: c.period,
    allowedUsers: c.allowedUsers,

    ans: c.ans,
    contractCode: c.contractCode,
    contractName: c.contractName,
    cnes: c.cnes,
    codification: c.codification,
    film: c.film,
    coparticipation: c.coparticipation,
    customProcedureViaPercentage: c.customProcedureViaPercentage,
    customProcedureVia: c.customProcedureVia,
    customProcedureViaPercentage2: c.customProcedureViaPercentage2,
    customProcedureVia2: c.customProcedureVia2,
    customProcedureViaPercentage3: c.customProcedureViaPercentage3,
    customProcedureVia3: c.customProcedureVia3,
    taxes: c.taxes,
    bankId: c.bankId,
    autoincrementLastLote: c.autoincrementLastLote,
    sendIntervalStartConsulta: c.sendIntervalStartConsulta,
    sendIntervalEndConsulta: c.sendIntervalEndConsulta,
    sendIntervalStartSadt: c.sendIntervalStartSadt,
    sendIntervalEndSadt: c.sendIntervalEndSadt,
    sendIntervalStartGhi: c.sendIntervalStartGhi,
    sendIntervalEndGhi: c.sendIntervalEndGhi,
    deadlineExpectancyConsulta: c.deadlineExpectancyConsulta,
    deadlineExpectancySadt: c.deadlineExpectancySadt,
    deadlineExpectancyGhi: c.deadlineExpectancyGhi,
    autoincrementLastGuiaConsulta: c.autoincrementLastGuiaConsulta,
    autoincrementLastGuiaSadt: c.autoincrementLastGuiaSadt,
    autoincrementLastGuiaGhi: c.autoincrementLastGuiaGhi,
    tissVersion: c.tissVersion,
    tissMethod: c.tissMethod,
    encodingXml: c.encodingXml,
    webserviceProviderType: c.webserviceProviderType,
    deadlineAttendance: c.deadlineAttendance,
    deliveryAddress: c.deliveryAddress,
    deliveryTime: c.deliveryTime,
    orderGuides: c.orderGuides,
    allowXml: c.allowXml,
    hideXmlTimezone: c.hideXmlTimezone,
    allowAuthorization: c.allowAuthorization,
    allowDelivery: c.allowDelivery,
    billSessionsSplitted: c.billSessionsSplitted,
    billSessionOpen: c.billSessionOpen,
    printProceduresAsList: c.printProceduresAsList,
    hidePrintGuidePrice: c.hidePrintGuidePrice,
    hideFinances: c.hideFinances,
    allowRepeatProcedures: c.allowRepeatProcedures,
    allowChangeProceduresDate: c.allowChangeProceduresDate,
    allowChangeMatmedsDate: c.allowChangeMatmedsDate,
    allowChangeProceduresTime: c.allowChangeProceduresTime,
    billGroupedProcedureTeam: c.billGroupedProcedureTeam,
    techniqueByProcedure: c.techniqueByProcedure,
    allowSequentialItem: c.allowSequentialItem,
    allowFixedPrice: c.allowFixedPrice,
    hideExecutantInfo: c.hideExecutantInfo,
    hideMainGuideNumber: c.hideMainGuideNumber,
    hideItemBilling: c.hideItemBilling,
    requiredGuideAuthorization: c.requiredGuideAuthorization,
    requiredGuideRequester: c.requiredGuideRequester,
    showPatientCpfLotResume: c.showPatientCpfLotResume,
    showAuthorizationDataOnGloss: c.showAuthorizationDataOnGloss,
    allowMatmedCustomRedAcr: c.allowMatmedCustomRedAcr,
    customProcedureViaOverPort: c.customProcedureViaOverPort,
    showPercentRedAcr: c.showPercentRedAcr,

    tomadorCnpj: c.tomadorCnpj,
    tomadorRazaoSocial: c.tomadorRazaoSocial,
    tomadorEnderecoCep: c.tomadorEnderecoCep,
    tomadorEnderecoEndereco: c.tomadorEnderecoEndereco,
    tomadorEnderecoNumero: c.tomadorEnderecoNumero,
    tomadorEnderecoComplemento: c.tomadorEnderecoComplemento,
    tomadorEnderecoUf: c.tomadorEnderecoUf,
    tomadorEnderecoIbge: c.tomadorEnderecoIbge,
    tomadorEnderecoBairro: c.tomadorEnderecoBairro,

    contatoSector: c.contatoSector,
    contatoName: c.contatoName,
    contatoEmail: c.contatoEmail,
    contatoPhone: c.contatoPhone,
    contatoSector2: c.contatoSector2,
    contatoName2: c.contatoName2,
    contatoEmail2: c.contatoEmail2,
    contatoPhone2: c.contatoPhone2,
    contatoSector3: c.contatoSector3,
    contatoName3: c.contatoName3,
    contatoEmail3: c.contatoEmail3,
    contatoPhone3: c.contatoPhone3,

    deadlineSendGlosa: c.deadlineSendGlosa,
    deadlineExpectancyGlosa: c.deadlineExpectancyGlosa,
    glosaMethod: c.glosaMethod,
  }
}

export const useConvenioForm = (convenioId?: string) => {
  const convenio = convenioId
    ? conveniosMock.find((c) => c.id === convenioId) ?? null
    : null

  const defaultValues = convenio ? convenioToForm(convenio) : emptyConvenio

  const form = useForm<ConvenioFormData>({
    resolver: zodResolver(convenioSchema),
    defaultValues,
  })

  return { form, convenio }
}
